### ISSUE TITLE
Bot doesn't show some Instagram previews properly

### ISSUE THREAD

**Issue by ccrowles** [pugson/telegram-twitter-url-expand-bot#24]
For some reason the bot doesn't show some Instagram previews properly, but when written and sent by a person it works.

Bot conversion of the link:
![Screenshot_20230304-122427_Plus_1](https://user-images.githubusercontent.com/12866474/222897291-4a4e992a-4082-4e24-9769-8978e168a3a5.png)

Same link, sent by me by manually adding the "dd":
![Screenshot_20230304-122450_Plus](https://user-images.githubusercontent.com/12866474/222897296-eff23c93-3659-4ec0-9ed4-ed154d5f9e0d.png)

**Comment by pugson** [comment]
Thanks, will look into it this week!

**Comment by pugson** [comment]
Looks like that reel was deleted @ccrowles. Got another link I could try this with?
