### ISSUE TITLE
fxtwitter is currently not working properly

### ISSUE THREAD

**Issue by devuterian** [pugson/telegram-twitter-url-expand-bot#44]
After elon made a number of changes, fxtwitter is currently not working properly at times.
I would like to request that this service revert back to vxtwitter, as replacing the link with vxtwitter often works fine. I could do a pull request, but I'm not good with code.. so I'm leaving it as an issue! I hope it gets fixed, as it's a really nice bot to use!

**Comment by devuterian** [comment]
In terms of functionality, fxtwitter is better than vxtwitter, but it often doesn't work at all. fxtwitter even sent out error messages, while vxtwitter was reliable.

Here's a screenshot showing an example of when vxtwitter works well when fxtwitter doesn't.

![screenshot](https://github.com/pugson/telegram-twitter-url-expand-bot/assets/49933873/ffa74af5-d93d-49fe-a63c-748031b6a4de)
 
![AyuGram_(2)_FFE5ugZ04N](https://github.com/pugson/telegram-twitter-url-expand-bot/assets/49933873/d7001195-ad55-4e49-9afa-a37346f7633e)

**Comment by pugson** [comment]
Got it, thanks. I think I will add a way to configure which service to use for each group chat so you can customize it.

**Comment by pugson** [comment]
https://github.com/FixTweet/FixTweet/issues/333#issuecomment-1686995922

> Most functionality of FixTweet that was lost has been restored:
-T.co link replacement
-NSFW Tweets
-Tweet translation

> The only thing that is still missing is the dynamic colors for Discord embeds, and unfortunately it seems Twitter is not giving out that data on the graphql endpoints, so we might be hosed there.

> Since almost all functionality is back, I'll go ahead and close this specific issue. Feel free to open another issue if you have other issues with any particular tweets!

Would you still want to use vxtwitter despite these changes? @devuterian

**Comment by pugson** [comment]
Feel free to re-open if you still think this is needed.
