### ISSUE TITLE
Feature Request: Add Support for Expanding Xiaohongshu (RED) Links

### ISSUE THREAD

**Issue by huwan** [pugson/telegram-twitter-url-expand-bot#60]
First off, thank you for developing such an incredibly useful tool! The Link Expander bot has been a great help for expanding links from various platforms. I would like to request a new feature: adding support for expanding links from Xiaohongshu (also known as RED), which is often referred to as the Chinese Instagram.

Xiaohongshu is a popular social media platform in China, and users often share links to posts on this platform. When sharing a post from Xiaohongshu, the links appear in the following formats:

1. Example 1: shared from Website.
    ```
    22 【『小红书官号』，薯队的小老弟们！ - 薯队长 | 小红书 - 你的生活指南】 😆 hzBWJ5nUsVMyNo2 😆 http://xhslink.com/y2NI7O
    ```
2. Example 2: shared from App.
    ```
    17 薯队长发布了一篇小红书笔记，快来看吧！ 😆 bmmrvJtMR7QZ7HC 😆 http://xhslink.com/Z4VI7O，复制本条信息，打开【小红书】App查看精彩内容！
    ```
It would be highly beneficial if the bot could:
1. Extract the Xiaohongshu link from the shared content.
2. Expand the shortened Xiaohongshu link (e.g., `http://xhslink.com/Z4VI7O`) to its full URL (e.g., `https://www.xiaohongshu.com/discovery/item/60ab7794000000002103deb0?source=webshare`).
3. Display a preview of the expanded link, similar to how it handles other supported platforms.

Thank you.

**Comment by pugson** [comment]
Is there a hosted service that can handle showing correct metadata?

The bot is using a URL replacement method (x.com to fxtwitter.com) and the external service is responsible for providing the embedded metadata.

**Comment by huwan** [comment]
Thank you for the clarification. I understand the current setup now. Unfortunately, I'm not aware of any providers that can handle Xiaohongshu (RED) links at this time. I'll go ahead and close this issue for now.
