### ISSUE TITLE
Instagram expansion broken

### ISSUE THREAD

**Issue by asampal** [pugson/telegram-twitter-url-expand-bot#62]
Now getting the following when posting IG links:

![image](https://github.com/user-attachments/assets/7f29a1f7-9a78-4e05-8f38-62d022b8e5fa)

**Comment by borng** [comment]
Wrong repo... goes in [instafix](https://github.com/Wikidepia/InstaFix)

**Comment by yo-honey** [comment]
Some links not expanding 

https://www.instagram.com/reel/C_DSYDqyWf2

https://www.ddinstagram.com/p/DDJSkDJq8an/
![Screenshot_20241207_192305_Plus](https://github.com/user-attachments/assets/2eea232f-b8e2-4de3-9afc-cf49064c4869)

**Comment by yo-honey** [comment]
@pugson

**Comment by pugson** [comment]
this is a problem with ddinstagram.com so i disabled the bot from handling ig reels

**Comment by yo-honey** [comment]
Please don't disable , atleast earlier only some reels was not working most reels was working
