### ISSUE TITLE
Spamming of service messages

### ISSUE THREAD

**Issue by Marocco2** [pugson/telegram-twitter-url-expand-bot#65]
I've set the lock command but for some reason it will keep spamming my group chat like `Link Expander:
You need to be an admin to change Autoexpand settings.` etc.
I would like to at least be able to silence those messages as I don't need to provide a notification of some sorts for my group members.

Thanks 🙏

**Comment by pugson** [comment]
i'm guessing it's because of people pressing the button from the bot's message. can you delete the message from the chat and see if it stops?

**Comment by Marocco2** [comment]
> i'm guessing it's because of people pressing the button from the bot's message. can you delete the message from the chat and see if it stops?

That's the thing: it never came up, but it keeps spamming that and for other settings
