### ISSUE TITLE
Ability to auto-expand every link and delete original message

### ISSUE THREAD

**Issue by pugson** [pugson/telegram-twitter-url-expand-bot#7]
# Requirements
- [x] Save chat id to a database
- [x] Bot Command for enabling the feature
- [x] Bot Command for disabling the feature
- [x] Sending commands saves a boolean field in the database along with chat id
- [x] Explainer about giving the bot admin rights for deleting messages to work
- [x] Looking up chat id and boolean from the database before deciding what to do with a link
- [x] Including the username of person who posted the original link in the expanded message
- [x] Copy text from original message and send it with the expanded link
- [x] Update readme

**Comment by lochie** [comment]
fuck yeah mate 🙌

**Comment by lochie** [comment]
nice
