### ISSUE TITLE
Configuration setting to remove original unexpanded post

### ISSUE THREAD

**Issue by asampal** [pugson/telegram-twitter-url-expand-bot#9]
It would be great if the bot could be configured to delete the original (unexpanded) post.

**Comment by pugson** [comment]
Working on that with #7. Or do you mean being able to configure the bot to delete the message when manually expanding a link? That's also a good idea.

**Comment by asampal** [comment]
Well, I understood #7 to address the issue of adding the bot to a group where there are already existing unexpanded links which you intend to expand in one shot.

In this issue I was focusing on just the last one posted. My intent would be to minimize as much of the unnecessary stuff that's there currently, after expansion. I guess some people would want a more fine-grained configuration wrt what you should end up with after the bot does its thing.

e.g. I most likely don't need the undo, or the original twitter.com link, if there is a vxtwitter.com link

**Comment by pugson** [comment]
Hey @asampal, the bot will now delete the original message with an unexpanded link after expanding when it has admin permissions to delete messages.

**Comment by pugson** [comment]
You can also let the bot automatically do that without confirming when you use the `/autoexpand` command to configure it per chat.

**Comment by asampal** [comment]
Great! Really appreciate it.
